# Generated by Django 6.0.6 on 2026-06-14 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English')], default='ru', max_length=2, verbose_name='Язык')),
                ('theme', models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная')], default='light', max_length=10, verbose_name='Тема')),
                ('currency', models.CharField(choices=[('RUB', '₽ Российский рубль'), ('USD', '$ Доллар США'), ('EUR', '€ Евро'), ('GBP', '£ Британский фунт'), ('JPY', '¥ Японская йена')], default='RUB', max_length=3, verbose_name='Валюта')),
                ('distance_unit', models.CharField(choices=[('km', 'Километры'), ('mi', 'Мили')], default='km', max_length=2, verbose_name='Единица расстояния')),
                ('temperature_unit', models.CharField(choices=[('C', '°C'), ('F', '°F')], default='C', max_length=1, verbose_name='Единица температуры')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email-уведомления')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Push-уведомления')),
                ('google_maps_api_key', models.CharField(blank=True, max_length=255, verbose_name='Google Maps API ключ')),
                ('google_calendar_connected', models.BooleanField(default=False, verbose_name='Google Calendar подключён')),
                ('apple_calendar_connected', models.BooleanField(default=False, verbose_name='Apple Calendar подключён')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Настройки пользователя',
                'verbose_name_plural': 'Настройки пользователей',
            },
        ),
    ]
