# Generated by Django 6.0.6 on 2026-06-14 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('flight', 'Авиабилет'), ('hotel', 'Отель'), ('train', 'Ж/Д'), ('car', 'Аренда авто'), ('other', 'Другое')], max_length=20, verbose_name='Тип бронирования')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('confirmation_number', models.CharField(blank=True, max_length=100, verbose_name='Номер подтверждения')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Начало')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Место')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость')),
                ('email_source', models.TextField(blank=True, verbose_name='Исходное письмо')),
                ('is_parsed', models.BooleanField(default=False, verbose_name='Спарсено из письма')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
    ]
